# Generated by Django 5.1 on 2024-09-04 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=450)),
                ('preco', models.IntegerField()),
                ('publicada', models.BooleanField(default=False)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.categoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
